---
  - name: Build Docker image
    hosts: all
    connection: ssh
    become: yes
    tasks:
      - name: copy files
        copy: 
          src: /home/devsr/opt/
          dest: /home/devsr/
        notify: build-doicker-image
    handlers:
      - name: build-doicker-image
        command: docker build -t uimage /home/devsr/
...
